export const products = [
    {
        name: "Airpods",
        description: "AirPods: Wireless earbuds by Apple, delivering seamless connectivity, crystal-clear sound, and effortless pairing with Apple devices. Enjoy freedom of movement and immersive audio in a sleek, compact design.",
        image: "../images/airpods.jpg",
        price: 399,
        rating: 0,
        brand: "Apple",
        category: "Electronics",
        numReviews: 0,
        countInStock: 8,
    },
    {
        name: "Alexa",
        description: "Alexa: Smart voice assistant by Amazon, offering hands-free convenience and a wide range of skills. Control your smart home, play music, get news updates, and more with just your voice.",
        image: "../images/alexa.jpg",
        price: 99,
        rating:0,
        brand: "Samsung",
        category: "Smart Home",
        numReviews: 0,
        countInStock: 15,
    },
    {
        name: "Camera",
        description: "Camera: High-quality digital camera for capturing memorable moments. Features advanced sensors, image stabilization, and various shooting modes to capture stunning photos and videos.",
        image: "../images/camera.jpg",
        price: 599,
        rating: 0,
        brand: "LG",
        category: "Photography",
        numReviews: 0,
        countInStock: 5,
    },
    {
        name: "Mouse",
        description: "Mouse: Ergonomic wireless mouse for precise and comfortable navigation. Offers smooth tracking, customizable buttons, and long battery life, enhancing productivity and reducing wrist strain.",
        image: "../images/mouse.jpg",
        price: 49,
        rating: 0,
        brand: "Microsoft",
        category: "Computer Accessories",
        numReviews: 6,
        countInStock: 20,
    },
    {
        name: "Phone",
        description: "Phone: Feature-packed smartphone with cutting-edge technology. Boasts a vibrant display, powerful processor, high-resolution camera, and a variety of apps for enhanced productivity and entertainment.",
        image: "../images/phone.jpg",
        price: 799,
        rating: 4.7,
        brand: "HP",
        category: "Electronics",
        numReviews: 15,
        countInStock: 10,
    },
    {
        name: "Playstation",
        description: "Playstation: Gaming console that offers immersive gaming experiences. Enjoy stunning graphics, online multiplayer, a vast library of games, and entertainment apps for endless entertainment.",
        image: "../images/playstation.jpg",
        price: 499,
        rating: 4.9,
        brand: "Dell",
        category: "Gaming",
        numReviews: 10,
        countInStock: 3,
    },
    {
        name: "Sample",
        description: "Sample: A versatile product that showcases the quality and functionality of our brand. Designed with precision and care to meet various needs and provide exceptional user experience.",
        image: "../images/sample.jpg",
        price: 29,
        rating: 4.2,
        brand: "Asus",
        category: "Miscellaneous",
        numReviews: 3,
        countInStock: 25,
    },
];
