export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ALL_ORDERS_DETAILS_REQUEST = "ALL_ORDERS_DETAILS_REQUEST"
export const ALL_ORDERS_DETAILS_SUCCESS = "ALL_ORDERS_DETAILS_SUCCESS"
export const ALL_ORDERS_DETAILS_FAIL = "ALL_ORDERS_DETAILS_FAIL"

export const ADMIN_GET_ALL_ORDERS_REQUEST = "ADMIN_GET_ALL_ORDERS_REQUEST"
export const ADMIN_GET_ALL_ORDERS_SUCCESS = "ADMIN_GET_ALL_ORDERS_SUCCESS"
export const ADMIN_GET_ALL_ORDERS_FAIL = "ADMIN_GET_ALL_ORDERS_FAIL"

export const ADMIN_DELIVER_ALL_ORDERS_REQUEST = "ADMIN_DELIVER_ALL_ORDERS_REQUEST"
export const ADMIN_DELIVER_ALL_ORDERS_SUCCESS = "ADMIN_DELIVER_ALL_ORDERS_SUCCESS"
export const ADMIN_DELIVER_ALL_ORDERS_FAIL = "ADMIN_DELIVER_ALL_ORDERS_FAIL"