export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL"

export const GET_PRODUCT_DETAIL_REQUEST = "GET_PRODUCT_DETAIL_REQUEST"
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL"

export const GET_ADMIN_ALL_PRODUCTS_REQUEST = "GET_ADMIN_ALL_PRODUCTS_REQUEST"
export const GET_ADMIN_ALL_PRODUCTS_SUCCESS = "GET_ADMIN_ALL_PRODUCTS_SUCCESS"
export const GET_ADMIN_ALL_PRODUCTS_FAIL = "GET_ADMIN_ALL_PRODUCTS_FAIL"

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST"
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS"
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL"

export const ADMIN_CREATE_PRODUCT_REQUEST = "ADMIN_CREATE_PRODUCT_REQUEST"
export const ADMIN_CREATE_PRODUCT_SUCCESS = "ADMIN_CREATE_PRODUCT_SUCCESS"
export const ADMIN_CREATE_PRODUCT_FAIL = "ADMIN_CREATE_PRODUCT_FAIL"
export const ADMIN_CREATE_PRODUCT_RESET = "ADMIN_CREATE_PRODUCT_RESET"

export const ADMIN_EDIT_PRODUCT_REQUEST = "ADMIN_EDIT_PRODUCT_REQUEST"
export const ADMIN_EDIT_PRODUCT_SUCCESS = "ADMIN_EDIT_PRODUCT_SUCCESS"
export const ADMIN_EDIT_PRODUCT_FAIL = "ADMIN_EDIT_PRODUCT_FAIL"
export const ADMIN_EDIT_PRODUCT_RESET = "ADMIN_EDIT_PRODUCT_RESET"

export const CREATE_PRODUCT_REVIEW_REQUEST = "CREATE_PRODUCT_REVIEW_REQUEST"
export const CREATE_PRODUCT_REVIEW_SUCCESS = "CREATE_PRODUCT_REVIEW_SUCCESS"
export const CREATE_PRODUCT_REVIEW_FAIL = "CREATE_PRODUCT_REVIEW_FAIL"
export const CREATE_PRODUCT_REVIEW_RESET = "CREATE_PRODUCT_REVIEW_RESET"