export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REG_REQUEST = "USER_REG_REQUEST"
export const USER_REG_SUCCESS = "USER_REG_SUCCES"
export const USER_REG_FAIL = "USER_REG_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"

export const ADMIN_USER_LIST_REQUEST = "ADMIN_USER_LIST_REQUEST"
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS"
export const ADMIN_USER_LIST_FAIL = "ADMIN_USER_LIST_FAIL"
export const ADMIN_USER_LIST_RESET = "ADMIN_USER_LIST_RESET"

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST"
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS"
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL"

export const ADMIN_USER_ID_REQUEST = "ADMIN_USER_ID_REQUEST"
export const ADMIN_USER_ID_SUCCESS = "ADMIN_USER_ID_SUCCESS"
export const ADMIN_USER_ID_FAIL = "ADMIN_USER_ID_FAIL"

export const ADMIN_USER_UPDATE_REQUEST = "ADMIN_USER_UPDATE_REQUEST"
export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS"
export const ADMIN_USER_UPDATE_FAIL = "ADMIN_USER_UPDATE_FAIL"