export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REG_REQUEST = "USER_REG_REQUEST"
export const USER_REG_SUCCESS = "USER_REG_SUCCES"
export const USER_REG_FAIL = "USER_REG_FAIL"